### ISSUE TITLE
Color Detector: Turns on when not connected to anything

### ISSUE THREAD

**Issue by jmcpeak2** [myjeeed/MakerWear#72] opened 2016-07-22 15:47 UTC
The white LED on the color detector turn on when the module is connected to the socket and has no module connected to its input.

In the code, the LED should only turn on if the input to the module is greater than 4.4 V. This must be a hardware issue, perhaps related to #20

**Comment by myjeeed** [comment] 2016-07-23 02:34
I think we did measure the voltage on the SIN pin, and it was almost 0 (similar to every other module)... but still worth checking if the problem is from the pull-down resistor. I personally think that it is a software issue, though it doesn't make sense at all :) It would be great if you could fix this.

Note that reprogramming the ColorDetector is a bit difficult as it is using those pins to communicate with the Color Sensor on top of the module, so you need to take off the ATtiny and reprogram it, and finally resolder it. So I highly suggest you to use one of those DIP 8 pin sockets on the module so that you could easily reprogram without soldering.

**Comment by myjeeed** [comment] 2016-10-01 16:27
This was fixed. Thanks!

Closing the issue

**Closed as completed by myjeeed** 2016-10-01 16:27 UTC
Labels: bug, hardware
